apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cicd
  namespace: cicd
  labels:
    app: nginx-cicd

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-cicd

  template:
    metadata:
      labels:
        app: nginx-cicd

    spec:
      containers:
        - name: nginx-cicd
          image: nginx:latest

          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 200Mi

          ports:
            - containerPort: 80
              name: nginx-cicd

          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10

          volumeMounts:
            - name: nginx-cm
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: nginx-cm
          configMap:
            name: nginx-cm
