apiVersion: v1
kind: Service
metadata:
  name: nginx-cicd-service
  namespace: cicd
spec:
  selector:
    app: nginx-cicd
  type: ClusterIP

  ports:
    - name: nginx-cicd-service
      protocol: TCP
      port: 80
      targetPort: 80
