name: Deploy NGINX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Verify Cluster
        run: |
          kubectl get nodes

      - name: Create Namespace
        run: |
          kubectl apply -f k8s/00-cicd-namespace.yaml

      - name: Deploy NGINX
        run: |
          kubectl apply -f k8s/01-cicd-deployment.yaml
          kubectl apply -f k8s/02-cicd-service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nginx-deployment -n cicd
          kubectl get all -n cicd
