# Github tion pipeline to deploy NGINX to Kubernetes cluster on push to main branch

name: Deploy NGINX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify Cluster
        run: |
          kubectl get nodes

      - name: Create Namespace
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Deploy NGINX
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nginx-deployment -n cicd
          kubectl get all -n cicd
